---
- name: Setup OSC-CSI
  hosts: bastion
  tasks:
    - name: download helm
      become: yes
      command: 
        cmd: /bin/bash -c "wget https://get.helm.sh/helm-v3.8.0-rc.1-linux-amd64.tar.gz && tar -zxvf helm-v3.8.0-rc.1-linux-amd64.tar.gz && mv linux-amd64/helm /usr/local/bin/helm && chmod +x /usr/local/bin/helm"
        creates: /usr/local/bin/helm
    - name: Install Helm-git
      command:
        cmd: helm plugin install https://github.com/aslafy-z/helm-git --version 0.11.1
        creates: ~/.local/share/helm/plugins/helm-git
    - name: Add OSC repo
      command:
        cmd: helm repo add osc git+https://www.github.com/outscale-dev/osc-bsu-csi-driver/@osc-bsu-csi-driver?ref=v0.0.14beta
    - name: Install osc-csi
      command: helm install osc-bsu-csi-driver osc/osc-bsu-csi-driver --namespace kube-system --set enableVolumeScheduling=true --set enableVolumeResizing=true --set enableVolumeSnapshot=true --set region=$OSC_REGION --set image.repository=outscale/osc-ebs-csi-driver --set image.tag=v0.0.14beta
