---
- name: Setup bastion
  hosts: bastion
  tasks:
    - name: Install software
      become: yes
      apt:
        update_cache: yes
        name:
          #- socat # for kubectl port-forward
          #- conntrack
          #- ipset
          - docker.io
    - name: download kubectl
      become: yes
      get_url:
        url: "https://dl.k8s.io/release/v1.21.6/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: 'a+rx'
    - name: create .kube folder
      file:
        path: /home/outscale/.kube
        state: directory
        mode: '0755'
    - name: Disable swap
      become: yes
      command: swapoff -a
    - name: Add outscale user to docker group
      become: yes
      user:
        name: outscale
        groups: docker
        append: yes
    - name: download helm
      become: yes
      command: 
        cmd: /bin/bash -c "wget https://get.helm.sh/helm-v3.8.0-rc.1-linux-amd64.tar.gz && tar -zxvf helm-v3.8.0-rc.1-linux-amd64.tar.gz && mv linux-amd64/helm /usr/local/bin/helm && chmod +x /usr/local/bin/helm"
