---
- name: Setup workers
  hosts: workers
  tasks:
    - name: Install software
      become: yes
      apt:
        update_cache: yes
        name:
          #- socat # for kubectl port-forward
          #- conntrack
          #- ipset
          - docker.io
    - name: Disable swap
      become: yes
      command: swapoff -a
    - name: Add outscale user to docker group
      become: yes
      user:
        name: outscale
        groups: docker
        append: yes
